### ISSUE TITLE
Asus BT400 [0B05:17CB]

### ISSUE THREAD

**Issue by dokterdok** [the-darkvoid/BrcmPatchRAM#1]
Hi the-darkvoid, 
Very interesting tool, thanks for making it!

I can't get BrcmPatchRAM v.0.3 to work however on my Asus BT400 dongle with vendorId: 0xb05 productId: 0x17cb. This dongle appears in the Info.plist. I'm using OS X 10.10.2 b2

Console output at system startup:

```
kernel[0]: BrcmPatchRAM::init
kernel[0]: BrcmPatchRAM::probe
kernel[0]: BrcmFirmwareStore::init
kernel[0]: BrcmFirmwareStore::probe
kernel[0]: BrcmFirmwareStore::start
kernel[0]: BrcmPatchRAM: Version 0.0.1 starting.
kernel[0]: BrcmPatchRAM: USB [0b05:17cb 5CF3706193F6 v274] "BCM20702A0" by "Broadcom Corp"
```

When I unplug and replug:

```
kernel[0]: BrcmFirmwareStore: Retrieved firmware for firmware key "BCM20702A1_001.002.014.1443.1612_v5708".
kernel[0]: BrcmFirmwareStore: Decompressed firmware (29714 bytes --> 70016 bytes).
kernel[0]: BrcmPatchRAM: device request failed (0xe000404f).
kernel[0]: BrcmPatchRAM: Failed to reset the device (0xe00002d5).
kernel[0]: BrcmPatchRAM: Unable to get device status (0xe000404f).
kernel[0]: BrcmPatchRAM: Firmware upgrade completed successfully.
```

The Bluetooth firmware version is stuck at v4096.
Am I doing something wrong? any ideas?
Side question: are IOBluetoothFamily DFUs compatible?

edit: corrected vendor id

**Comment by the-darkvoid** [comment]
Asus BT-400 is now properly supported.
