### ISSUE TITLE
Format of BrcmFirmwareStore/Firmwares in Info.plist issues...

### ISSUE THREAD

**Issue by RehabMan** [the-darkvoid/BrcmPatchRAM#11]
I notice that if I touch anything in the Info.plist with the xcode plist editor, that all of these firmware <data> entries are rewritten with different formatting resulting in gigantic diffs.

What are you using to edit the Info.plist?  Should we "bite the bullet" and reformat it as xcode likes with an individual commit, such that the plist can be edited with xcode?

**Comment by the-darkvoid** [comment]
@RehabMan,

Currently using PlistEdit Pro, since I think plist editing in Xcode is not to intuitive.
But I see your problem. Next firmware update batch I will do it in Xcode.
