### ISSUE TITLE
Problem on 0a5c_21de

### ISSUE THREAD

**Issue by duguzuyang** [the-darkvoid/BrcmPatchRAM#13]
![2015-03-14 7 35 40 pm](https://cloud.githubusercontent.com/assets/7322443/6651517/58aafc50-ca81-11e4-90bf-387c0a737cc4.png)

![2015-03-14 7 36 36 pm](https://cloud.githubusercontent.com/assets/7322443/6651520/7690a198-ca81-11e4-95ba-17f5158cc3d7.png)

#Problem:

There is Bluetooth icon but can not connect to any Bluetooth device (phones, Trackpads, etc)

#BrcmPatchRAM version: 
1.41

#pid & uid: 
0a5c_21de

#log:

Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.42 seconds.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.24 seconds.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.51 seconds.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.28 seconds.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.48 seconds.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.30 seconds.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.23 seconds.
Mar 14 19:28:09 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.30 seconds.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.35 seconds.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.26 seconds.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.33 seconds.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.64 seconds.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.40 seconds.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.29 seconds.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.30 seconds.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.35 seconds.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.31 seconds.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.28 seconds.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.21 seconds.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.43 seconds.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.43 seconds.
Mar 14 19:28:10 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.23 seconds.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.48 seconds.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.52 seconds.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.26 seconds.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.40 seconds.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.39 seconds.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.23 seconds.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Processing time 0.32 seconds.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:28:11 ZuyangdeiMac kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:30:03 localhost kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:30:03 localhost kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:30:03 localhost kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:30:03 localhost kernel[0]: BrcmPatchRAM: Processing time 0.42 seconds.
Mar 14 19:30:03 localhost kernel[0]: BrcmPatchRAM: [0a5c:21de]: Published new IOKit personality.
Mar 14 19:30:05 localhost kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 14 19:30:05 localhost kernel[0]: BrcmPatchRAM: [0a5c:21de]: USB [20689DD163AF v274] "BCM20702A0" by "Broadcom Corp"
Mar 14 19:30:05 localhost kernel[0]: BrcmPatchRAM: [0a5c:21de]: Firmware upgrade completed successfully.
Mar 14 19:30:05 localhost kernel[0]: BrcmPatchRAM: Processing time 0.24 seconds.
Mar 14 19:30:05 localhost kernel[0]: BrcmPatchRAM: [0a5c:21de]: Found existing IOKit personality "com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport".

**Comment by duguzuyang** [comment]
And I don't understand why it tried upgrade firmware so many times( I only post a part of the log, the complete log is much longer)

**Comment by duguzuyang** [comment]
Funny thing is that it CAN connect to a Bluetooth speaker and it works fine

**Comment by RehabMan** [comment]
Any version later than 1.4 should be considered a work-in-progress...

Try the latest version.  Build from current sources at my fork: https://github.com/RehabMan/OS-X-BrcmPatchRAM.  Use the debug version to get more detailed logs.

If your system is probing BrcmPatchRAM continuously it points to a problem...

**Comment by duguzuyang** [comment]
Problem solved. I just reinstall all Apple's original kexts related to bluetooth.


Thanks a lot, BrcmPatchRAM is really working fine.

**Comment by RehabMan** [comment]
This issue can be closed.
