### ISSUE TITLE
BT Handoff Lenovo china

### ISSUE THREAD

**Issue by R4tch3t** [the-darkvoid/BrcmPatchRAM#15]
Mar 22 09:56:54 Victors-MacBook-Pro kernel[0]: BrcmPatchRAM: Version 1.4.1 starting on OS X Darwin 14.1.
Mar 22 09:56:54 Victors-MacBook-Pro kernel[0]: BrcmPatchRAM: [0489:e042]: USB [08EDB9D6C0B0 v274] "BCM20702A0" by "Broadcom Corp"
Mar 22 09:56:54 Victors-MacBook-Pro kernel[0]: BrcmPatchRAM: Retrieved firmware for firmware key "BCM20702A1_001.002.014.1443.1484_v5580".
Mar 22 09:56:54 Victors-MacBook-Pro kernel[0]: BrcmPatchRAM: Decompressed firmware (29590 bytes --> 69661 bytes).
Mar 22 09:56:54 Victors-MacBook-Pro kernel[0]: BrcmPatchRAM: Firmware is valid IntelHex firmware.
Mar 22 09:56:56 Victors-MacBook-Pro kernel[0]: BrcmPatchRAM: [0489:e042]: Not responding - Delaying next read.
Mar 22 09:56:56 Victors-MacBook-Pro kernel[0]: BrcmPatchRAM: [0489:e042]: readCompletion - Return aborted (0xe00002eb)
Mar 22 09:56:56 Victors-MacBook-Pro kernel[0]: BrcmPatchRAM: [0489:e042]: Firmware upgrade completed successfully.
Mar 22 09:56:56 Victors-MacBook-Pro kernel[0]: BrcmPatchRAM: Processing time 0.785 seconds.
Mar 22 09:56:56 Victors-MacBook-Pro kernel[0]: BrcmPatchRAM: [0489:e042]: Found existing IOKit personality "com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport".

but the result is the next:

Bluetooth Low Energy Supported:	Yes
  Handoff Supported:	No
  Instant Hotspot Supported:	No
  Manufacturer:	Broadcom
  Transport:	USB
  Chipset:	Unknown (ffff)
  Firmware Version:	v14 c5580
  Bluetooth Power:	Off
  Discoverable:	Off
  Auto Seek Pointing:	Off
  Remote wake:	On
  Vendor ID:	0x0489
  Product ID:	0xE042
  HCI Version:	0x6
  HCI Revision:	0x15CC
  LMP Version:	0x6
  LMP Subversion:	0x220E
  Auto Seek Keyboard:	Off

**Comment by RehabMan** [comment]
You need a patch to IOBluetoothFamily to enable handoff/hotspot.  It has nothing to do with firmware loading.

See here: http://www.tonymacx86.com/network/104850-guide-airport-pcie-half-mini-v2.html

**Comment by MegaCookie** [comment]
Try to put this in the KernelAndKextPatches --> KextsToPatch Array:
```plist
<dict>
	<key>Name</key>
	<string>IOBluetoothFamily</string>
	<key>Find</key>
	<data>SIXAdFwPt0g=</data>
	<key>Replace</key>
	<data>Qb4PAAAA61k=</data>
	<key>Comment</key>
	<string>Handoff Fix</string>
</dict>
```

**Comment by the-darkvoid** [comment]
@RehabMan & @MegaCookie  are correct.

It requires a Clover or Kext patch and is outside the functionality provided by BrcmPatchRAM.
