### ISSUE TITLE
Fail to work in OS 10.11

### ISSUE THREAD

**Issue by lisai9093** [the-darkvoid/BrcmPatchRAM#19]
Bluetooth is grey out showing: bluetooth unavailable.

Any idea?

Thx.

**Comment by mariusvictorbach** [comment]
Sounds like "early adopters syndrome" ;-)

**Comment by theracermaster** [comment]
Look here: http://www.insanelymac.com/forum/topic/306632-broadcom-bluetooth-20702a/#entry2144734

**Comment by RehabMan** [comment]
Duplicate of https://github.com/RehabMan/OS-X-BrcmPatchRAM/issues/3

**Comment by RehabMan** [comment]
Use BrcmBluetoothInjector.kext from my fork of this repo.

**Comment by RehabMan** [comment]
BrcmPatchRAM2.kext is available for testing.

https://bitbucket.org/RehabMan/os-x-brcmpatchram/downloads

**Comment by the-darkvoid** [comment]
Closed with usbhost branch and pull request #24.
