### ISSUE TITLE
Cannot find "BrcmFirmwareStore"

### ISSUE THREAD

**Issue by KazWolfe** [the-darkvoid/BrcmPatchRAM#31]
My El Capitan Hackintosh is not able to find BrcmFirmwareStore:

<pre><code>
Oct 27 17:12:07 localhost kernel[0]: BrcmPatchRAM2: Version 2.2.1 starting on OS X Darwin 15.0.
Oct 27 17:12:07 localhost kernel[0]: BrcmPatchRAM2: Published new IOKit personality for BrcmFirmwareStore.
Oct 27 17:12:09 localhost kernel[0]: BrcmPatchRAM2: [13d3:3435]: BrcmFirmwareStore does not appear to be available.
Oct 27 17:12:09 localhost kernel[0]: BrcmPatchRAM2: [13d3:3435]: USB [54271E9199FE v274] "BCM20702A0" by "Broadcom Corp"
Oct 27 17:12:09 localhost kernel[0]: BrcmPatchRAM2: [13d3:3435]: Firmware upgrade not needed.
Oct 27 17:12:09 localhost kernel[0]: BrcmPatchRAM2: [13d3:3435]: Published new IOKit personality.
Oct 27 17:12:09 localhost kernel[0]: BrcmPatchRAM2: Processing time 2.16 seconds.
Oct 27 17:12:09 localhost kernel[0]: BrcmPatchRAM2: Version 2.2.1 starting on OS X Darwin 15.0.
Oct 27 17:12:09 localhost kernel[0]: BrcmPatchRAM2: unable to find disabled BrcmFirmwareStore personality.
Oct 27 17:12:11 localhost kernel[0]: BrcmPatchRAM2: [13d3:3435]: BrcmFirmwareStore does not appear to be available.
Oct 27 17:12:11 localhost kernel[0]: BrcmPatchRAM2: [13d3:3435]: USB [54271E9199FE v274] "BCM20702A0" by "Broadcom Corp"
Oct 27 17:12:11 localhost kernel[0]: BrcmPatchRAM2: [13d3:3435]: Firmware upgrade not needed.
Oct 27 17:12:11 localhost kernel[0]: BrcmPatchRAM2: [13d3:3435]: Found existing IOKit personality "com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport".
Oct 27 17:12:11 localhost kernel[0]: BrcmPatchRAM2: Processing time 2.6 seconds.
</code></pre>

`BrcmFirmwareRepo.kext` is installed in `/S/L/E`, and was placed there by Kext Wizard. I have tried reinstalling numerous times already.

-----

Chip is `BCM94352HMB` by AzureWave (`13D3:3435`)

**Comment by RehabMan** [comment]
Rebuild cache:
```
sudo touch /System/Library/Extensions && sudo kextcache -u /
```
