### ISSUE TITLE
0a5c:22be cannot get it working

### ISSUE THREAD

**Issue by ComputerSpecialist** [the-darkvoid/BrcmPatchRAM#32]
Hi, I have been trying all day to make this bluetooth adapter work. It is a mini pic wifi/bluetooth combo card, I have no issues with the wifi that works fine.

But I cannot get the bluetooth to work in 10.10.2, 10.10.5, 10.11 or 10.11.2

right now I am trying BrcmPatchRAM in S/L/E in 10.11 because BTFirmwareUploader showed it updated the firmware but still it is not detecting a bluetooth device.

I can only get the bluetooth device detected in 10.10.2 sometimes when I switch from w10 to 10.10.2, but then it won't find any devices.

I attached my system.log from 10.11 with BrcmPatchRAM and the Repofirmware kext in S/L/E

I hope you can help me

I installed version 2015-1101 from here:

https://bitbucket.org/RehabMan/os-x-brcmpatchram/downloads

I also have problems with loading the drivers in windows sometimes other times it works fine, you can see in attached screenshots.

this is my log from 10.11 with the release version, I cannot find the debug version also where is the BrcmBluetoothInjector.kext? Would like to try that one out too.

[system.log.txt](https://github.com/the-darkvoid/BrcmPatchRAM/files/75243/system.log.txt)

And here is my log from 10.10.2 without BcrmPatchRAM installed, but this is the best result I got, but it is not detecting devices in this situation:

[system-10.10.2.log.txt](https://github.com/the-darkvoid/BrcmPatchRAM/files/75273/system-10.10.2.log.txt)

here is my system report in 10.10.2:

[sysinfo.zip](https://github.com/the-darkvoid/BrcmPatchRAM/files/75275/sysinfo.zip)

I hope someone can help me

![bluetooth10 10 2](https://cloud.githubusercontent.com/assets/13680083/12059074/82a1fdde-af54-11e5-9726-351cef306c9e.png)
![bluetoothworkinginwindows](https://cloud.githubusercontent.com/assets/13680083/12059095/daf12a46-af54-11e5-86dc-a8fd556fd929.png)
![wifi1](https://cloud.githubusercontent.com/assets/13680083/12059101/efc55e88-af54-11e5-9828-0809bd2aa23e.jpg)
![wifi2](https://cloud.githubusercontent.com/assets/13680083/12059102/f4ec3e18-af54-11e5-99d9-099a83644020.jpg)
![windowsproblem](https://cloud.githubusercontent.com/assets/13680083/12058840/dde1ab9e-af50-11e5-8940-566a0be36665.png)
![btfirmwareuploader kext](https://cloud.githubusercontent.com/assets/13680083/12058867/326c9da4-af51-11e5-9224-423f5c9191c7.jpg)

**Comment by RehabMan** [comment]
0a5c:22be not supported.

**Comment by ComputerSpecialist** [comment]
Here it is supported:


http://forum.osxlatitude.com/index.php?/topic/2925-bluetooth-firmware-uploader/


Verzonden vanuit Outlook Mobile






On Fri, Feb 5, 2016 at 1:50 PM -0800, "RehabMan" <notifications@github.com> wrote:





0a5c:22be not supported.

---

**Comment by RehabMan** [comment]
Irrelevant.

BTFirmwareUploader.kext not related to BrcmPatchRAM.  Also not open source.

**Comment by ComputerSpecialist** [comment]
Thanks for the reply but now working on another hackintosh laptop. Asus X77JQ. But I have a serious video problem. It is working in Mavericks, but in Yosemite and El Capitan I have weird  color issue. problem also occurs after waking from sleep in Mavericks.


 I hope you can help me with this problem I can provide all information needed.


Kind regards,


Igor






On Sat, Feb 6, 2016 at 2:54 PM -0800, "RehabMan" <notifications@github.com> wrote:





Irrelevant.

BTFirmwareUploader.kext not related to BrcmPatchRAM.  Also not open source.

---

**Comment by RehabMan** [comment]
> But I have a serious video problem. 

Off-topic. Not related to BrcmPatchRAM. Use the forums.
